In [1]:
import pandas as pd
import numpy as np

In [2]:
df_movie=pd.read_excel(r'C:\Users\solan\OneDrive\Desktop\Sample\Movie data.xlsx')
df_part=df_movie
df_part.rename(columns={'IMDb Score (1-10)':'IMDb'})

,Title Count,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb,Total Reviews,Duration (min),Gross Revenue,Budget
0,1,Over the Hill to the Poorhouse,1920-09-15,Black and White,Crime,English,USA,Not Rated,Stephen Carr,Harry F. Millarde,2,4,0,0.0,4.8,1,110,3000000.0,100000.0
1,1,Metropolis,1927-01-26,Black and White,Drama,German,Germany,Not Rated,Brigitte Helm,Fritz Lang,136,203,756,12000.0,8.3,260,145,26435.0,6000000.0
2,1,The Broadway Melody,1929-11-11,Black and White,Musical,English,USA,Passed,Anita Page,Harry Beaumont,77,109,4,167.0,6.3,36,100,2808000.0,379000.0
3,1,42nd Street,1933-08-29,Black and White,Comedy,English,USA,Unrated,Ginger Rogers,Lloyd Bacon,610,995,24,439.0,7.7,65,89,2300000.0,439000.0
4,1,Top Hat,1935-04-15,Black and White,Comedy,English,USA,Approved,Ginger Rogers,Mark Sandrich,610,824,10,1000.0,7.8,66,81,3000000.0,609000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3720,1,Unfinished Business,2015-02-25,Color,Comedy,English,USA,R,Tom Wilkinson,Ken Scott,1000,1564,31,0.0,5.4,90,91,10214013.0,35000000.0
3721,1,Vacation,2015-08-03,Color,Adventure,English,USA,R,Chris Hemsworth,John Francis Daley,26000,40312,0,28000.0,6.1,204,99,58879132.0,31000000.0
3722,1,Victor Frankenstein,2015-03-08,Color,Drama,English,USA,PG-13,Daniel Radcliffe,Paul McGuigan,11000,12876,118,11000.0,6.0,159,110,5773519.0,40000000.0
3723,1,We Are Your Friends,2015-05-14,Color,Drama,English,UK,R,Vanessa Lengies,Max Joseph,804,3013,31,0.0,6.1,158,96,3590010.0,2000000.0
3724,1,Woman in Gold,2015-02-17,Color,Biography,English,UK,PG-13,Ryan Reynolds,Simon Curtis,16000,17866,64,34000.0,7.3,203,109,33305037.0,11000000.0

In [3]:
#1. Set up a view to show Budget by Title (as rows), with filters for Country (set to Japan) and Language (set to English). How many Japanese movies in the database were produced in English?																									
#2. Clear the Language filter, set the Country filter to Denmark, and pull in Gross Revenue as a second metric.																									
#3. Use the "Clear All" command in the PivotTable Analyze options to remove all fields from the table, and create a new view showing Gross Revenue by Country (as rows) and Genre (as columns). How much revenue was generated by Comedy films in Finland?																									
#4. Remove the Country field, move Genre to the row labels, and drag in Rating as secondary row labels. How much revenue was generated by PG-rated Family films? Double click on the cell to see the exact source data populating the value. Which title drove most of the revenue?

In [9]:
df_p1=df_part[['Title','Budget','Country','Language']]

In [10]:
df_p1[(df_p1.Language=='English') & (df_p1.Country=='Japan')].pivot(index='Title',columns='Country',values='Budget').head(10)

Country                      Japan
Title
One Missed Call         27000000.0
Street Fighter          35000000.0
The Quick and the Dead  32000000.0
Tora! Tora! Tora!              NaN
Trainwreck              35000000.0

In [11]:
df_p2=df_part[['Title','Budget',"Country",'Language','Gross Revenue']]

In [13]:
df_p2[(df_p2.Country=='Denmark')].pivot_table(df_p2,index="Title",aggfunc=[np.sumdf_p3=df_part[['Title','Budget',"Country",'Language','Gross Revenue','Genre']]
df_p3.pivot_table(df_p3,index='Country',columns='Genre').replace(np.nan,"")],margins=True,margins_name="Grand Total")

                                sum
                             Budget Gross Revenue
Title
A Lego Brickumentary      1000000.0      100240.0
Dancer in the Dark       12800000.0     4157491.0
Flame and Citron         45000000.0      145109.0
Manderlay                14200000.0       74205.0
Melancholia               7400000.0     3029870.0
Only God Forgives         4800000.0      778565.0
Smilla's Sense of Snow   35000000.0     2221994.0
The Celebration           1300000.0     1647780.0
The Hunt                  3800000.0      610968.0
Grand Total             125300000.0    12766222.0

In [14]:
df_p3=df_part[['Title','Budget',"Country",'Language','Gross Revenue','Genre']]
df_p3.pivot_table(df_p3,index='Country',columns='Genre').replace(np.nan,"")

                     Budget                                         \
Genre                Action    Adventure    Animation    Biography
Country
Afghanistan
Argentina
Aruba               3.5e+07
Australia       4.50615e+07  4.12917e+07     1.35e+08    1.175e+07
Belgium                          3.4e+07                   1.5e+07
Brazil                4e+06
Canada             6.08e+07      3.8e+07                   1.3e+07
Chile                                                      2.6e+07
China           1.25329e+08                                2.3e+07
Colombia
Czech Republic
Denmark             3.5e+07
Finland
France          3.94926e+07    8.542e+07      8.8e+06  2.97757e+07
Georgia               2e+07
Germany         4.80417e+07      7.5e+07      5.1e+07    1.375e+07
Hong Kong       2.99182e+07
Hungary                            2e+07
Iceland
India           3.09013e+08      1.2e+07
Indonesia           1.1e+06
Iran                1.4e+07
Ireland             2.3e+07                                1.7e+07
Israel                                        1.5e+06
Italy                200000
Japan           7.16087e+08   6.1925e+08
Mexico                             2e+06
Netherlands
New Line
New Zealand        1.15e+08    1.255e+08                   1.5e+07
Norway
Official site
Peru                4.5e+07
Philippines
Poland
Romania
Russia                2e+07        2e+07
South Africa        1.6e+07
South Korea       2.425e+07
Spain             1.135e+07        7e+07                   2.3e+07
Sweden
Taiwan              1.5e+07
Thailand         2.2725e+08
UK              4.69984e+07   5.7318e+07     4.25e+07   1.9176e+07
USA             6.94771e+07  6.47106e+07  5.86981e+07  2.85066e+07
West Germany                     1.4e+07

                                                                    \
Genre                Comedy        Crime  Documentary        Drama
Country
Afghanistan                                                  46000
Argentina                        1.5e+06                   1.7e+06
Aruba
Australia       1.17083e+07      8.5e+06                 3.898e+07
Belgium
Brazil                4e+06      3.3e+06                  3.45e+06
Canada          1.04062e+07     1.75e+07      1.2e+06  1.28083e+07
Chile
China                                                    3.528e+07
Colombia                           3e+06
Czech Republic    8.445e+07        5e+07
Denmark                          8.8e+06        1e+06    1.434e+07
Finland            3.85e+06
France          3.16364e+07     1.66e+07  6.93333e+07  2.18882e+07
Georgia
Germany         2.53722e+07   2.8875e+07               2.77556e+07
Hong Kong                                                  1.1e+07
Hungary                                                    2.5e+09
Iceland               1e+07                                3.8e+06
India           5.28333e+07                    300000  1.43244e+08
Indonesia
Iran                                                        230000
Ireland             1.7e+07                            8.39333e+06
Israel              1.5e+06                    450000
Italy           2.23333e+07    2.175e+07                   9.6e+06
Japan             2.025e+07        1e+06                  1.19e+07
Mexico             3.15e+06                            7.44554e+06
Netherlands                      4.5e+06                  1.25e+07
New Line              9e+07
New Zealand                                                6.5e+06
Norway          1.20667e+07     3.03e+07
Official site                                              1.5e+07
Peru
Philippines
Poland                                                     2.4e+06
Romania             1.2e+07                                 590000
Russia
South Africa                                               2.5e+07
South Korea     6.11445e+09      4.2e+09                     3e+06
Spain              1.05e+07     1.25e+07                     8e+07
Sweden              2.5e+07
Taiwan
Thailand
UK              1.48279e+07   2.3995e+07  2.66667e+06  1.70818e+07
USA             2.38697e+07  2.65123e+07  4.72671e+06  2.52594e+07
West Germany

                                          ... Gross Revenue              \
Genre                Family      Fantasy  ...         Drama      Family
Country                                   ...
Afghanistan                               ...   1.12733e+06
Argentina                                 ...   1.02358e+07
Aruba                                     ...
Australia                                 ...   3.00724e+07
Belgium                                   ...
Brazil                                    ...   2.80784e+06
Canada                          1.05e+07  ...   8.59746e+06
Chile                                     ...
China                                     ...   3.21776e+06
Colombia                                  ...
Czech Republic                   1.2e+07  ...
Denmark                                   ...   1.10159e+06
Finland                                   ...
France                                    ...   1.44221e+07
Georgia                                   ...
Germany                                   ...   1.46379e+07
Hong Kong                                 ...        564130
Hungary                                   ...        195888
Iceland                                   ...         19959
India                                     ...   2.81744e+06
Indonesia                                 ...
Iran                                      ...   2.89922e+06
Ireland                                   ...   8.22151e+06
Israel                                    ...
Italy                                     ...   3.92027e+06
Japan                                     ...         48856
Mexico                                    ...   3.47701e+06
Netherlands                               ...   2.47063e+06
New Line                                  ...
New Zealand                               ...   3.04654e+07
Norway                                    ...
Official site                             ...   2.02189e+07
Peru                                      ...
Philippines                               ...
Poland                                    ...        978908
Romania                                   ...   1.18578e+06
Russia                           4.2e+06  ...
South Africa                              ...    4.5089e+07
South Korea                               ...   2.18129e+06
Spain                                     ...   9.16736e+06
Sweden                                    ...
Taiwan                                    ...
Thailand                                  ...
UK                                 1e+06  ...   1.91391e+07
USA             1.48333e+07  1.87357e+07  ...   3.54711e+07  1.4916e+08
West Germany                              ...

                                                                   \
Genre               Fantasy       Horror     Musical      Mystery
Country
Afghanistan
Argentina
Aruba
Australia                    2.47301e+07              4.71746e+06
Belgium
Brazil
Canada          4.12641e+07  2.03495e+07                   489220
Chile
China
Colombia
Czech Republic  2.06095e+06
Denmark
Finland
France                       1.82914e+06              1.55232e+07
Georgia
Germany                      3.05246e+07              1.72665e+07
Hong Kong
Hungary
Iceland
India
Indonesia
Iran
Ireland
Israel
Italy                             238002
Japan                        2.68765e+07
Mexico
Netherlands
New Line
New Zealand
Norway
Official site
Peru
Philippines
Poland
Romania
Russia          1.48748e+06
South Africa
South Korea
Spain                              32566              1.86537e+07
Sweden
Taiwan
Thailand
UK               1.4564e+07  2.78909e+07
USA              4.3379e+07  3.78106e+07  9.2084e+07  6.47988e+07
West Germany


Genre               Romance       Sci-Fi Thriller      Western
Country
Afghanistan
Argentina
Aruba
Australia
Belgium
Brazil
Canada                             56129
Chile
China
Colombia
Czech Republic
Denmark
Finland
France
Georgia
Germany
Hong Kong
Hungary
Iceland
India                129319                 49000
Indonesia
Iran
Ireland
Israel
Italy
Japan
Mexico
Netherlands
New Line
New Zealand
Norway
Official site
Peru
Philippines                                 70071
Poland
Romania
Russia
South Africa
South Korea
Spain
Sweden
Taiwan
Thailand
UK
USA             3.12648e+07  2.97884e+07     2468  2.08219e+07
West Germany

[46 rows x 34 columns]

In [17]:
df_p4=df_part[['Title','Gross Revenue','Genre','Rating']]
df_p4[(df_p4.Genre=='Family') & (df_p4.Rating.isin(['G','PG']))].pivot_table(df_p4,index=['Genre','Rating']).replace(np.nan,"")

               Gross Revenue
Genre  Rating
Family G           2119994.0
       PG        222680719.5